# 项目相关配置
ruoyi:
  # 名称
  name: ruoyi
  # 版本
  version: 3.8.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径，以uploadPath结尾 示例（ Windows配置 D:/uploadPath，Linux配置 /uploadPath）
  profile: /var/data/java/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

spring:
  profiles:
    active: druid
  application:
    name: admin
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # redis 配置
  redis:
    # 地址
    host: 116.62.103.149
    # 端口
    port: 6379
    # 连接超时时间 2s
    timeout: 2000
  # 邮箱服务设置
  #  mail:
  #    host: smtp.qq.com #这个是QQ邮箱的，发件人邮箱的 SMTP 服务器地址, 必须准确, 不同邮件服务器地址不同, 一般(只是一般, 绝非绝对)格式为: smtp.xxx.com，可以百度
  #    username: 859425698@qq.com #qq邮箱
  #    password: ENC(s/5BB05S8Mp9qfgr5A2O3/G0B0A6iT4/uqU1x0ZeQrk=)  #qq邮箱授权码
  #    protocol: smtp #发送邮件协议
  #    default-encoding: utf-8
  #    port: 587
  #    properties:
  #      mail.smtp.auth: true
  #      mail.smtp.starttls.enable: true
  #      mail.smtp.starttls.required: true
  #      mail.smtp.socketFactory.port: 465
  #      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  #      mail.smtp.socketFactory.fallback: false
  rabbitmq:
    ####连接地址
    host: 116.62.103.149
    ####端口号
    port: 5672
    ####账号
    username: ENC(3RFP9UyB8GFped3pc4AFSQ==)
    ####密码
    password: ENC(3RFP9UyB8GFped3pc4AFSQ==)
  security:
    user:
      name: ENC(3RFP9UyB8GFped3pc4AFSQ==)
      password: ENC(aCnej7rWZ1AUhl+X1aLc3w==)
  # mqtt 配置
  mqtt:
    username: admin                            # 账号
    password: xjhqre                           # 密码
    host-url: tcp://1.15.88.204:1883           # mqtt连接tcp地址
    client-id: ${random.int}                   # ${random.int} 客户端Id，不能相同，采用随机数 ${random.value}
    default-topic: test                        # 默认主题
    timeout: 30                                # 超时时间
    keepalive: 60                              # 保持连接
    clearSession: true                         # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)

# MyBatis-plus配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      # 雪花算法生成 ID
      id-type: ASSIGN_ID
  type-handlers-package: com.xjhqre.iot.mybatisConfig

# 日志配置
logging:
  level:
    com.xjhqre.admin: debug

# 端口号
server:
  port: 8081

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# 阿里云oss配置信息
aliyun:
  oss:
    bucketName: xjhqre-bbs
    endPoint: https://oss-cn-hangzhou.aliyuncs.com
    keyId: ENC(QBNQCaGYNuKbmPkKvlOzd6yVCIwNZJtfdf4dxGL+fV67fu5p3lQV+Q==)
    keySecret: ENC(LX+q0PTTDBdLsKpUy263qJpMACr5e4VnglaGXf0VnKGzk36es6lidQ==)

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /admin/system/notice/*
  # 匹配链接
  urlPatterns: /admin/*,/monitor/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true